### ISSUE TITLE
Add logo to all pages

### ISSUE THREAD

**Issue by ghtmtt** [OleVik/grav-plugin-presentation#13]
HI,

is there an option to quick add a logo (copyright, company-logo) to one of the corner to all the slides?

**Comment by pcav** [comment]
I think this should be done using a background image. I tried adding one from `user/pages/images/`

```
Server Error

Sorry, something went terribly wrong!
E_RECOVERABLE_ERROR - Object of class stdClass could not be converted to string
For further details please review your logs/ folder, or enable displaying of errors in your system configuration.
```

**Comment by pcav** [comment]
[2019-11-25 15:22:06] grav.CRITICAL: Object of class stdClass could not be converted to string - Trace: #0 /usr/local/src/grav-faunalia/system/src/Grav/Common/Debugger.php(352): Whoops\Run->handleError(4096, 'Object of class...', '/usr/local/src/...', 96) #1 /usr/local/src/grav-faunalia/user/plugins/presentation/classes/Utilities.php(96): Grav\Common\Debugger->deprecatedErrorHandler(4096, 'Object of class...', '/usr/local/src/...', 96, Array) #2 /usr/local/src/grav-faunalia/user/plugins/presentation/classes/Parser.php(156): Grav\Plugin\PresentationPlugin\Utilities::explodeFileLocations(Array, '/usr/local/src/...', '/', '/') #3 /usr/local/src/grav-faunalia/user/plugins/presentation/classes/Parser.php(124): Grav\Plugin\PresentationPlugin\API\Parser->styleProcessor('presentation', 'background-imag...', 'logo_faunalia.j...', Array) #4 /usr/local/src/grav-faunalia/user/plugins/presentation/presentation.php(179): Grav\Plugin\PresentationPlugin\API\Parser->processor(Array, 'presentation', Array, 'style') #5 /usr/local/src/grav-faunalia/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Grav\Plugin\PresentationPlugin->pageIteration(Object(RocketTheme\Toolbox\Event\Event), 'onPageContentPr...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #6 /usr/local/src/grav-faunalia/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPageContentPr...', Object(RocketTheme\Toolbox\Event\Event)) #7 /usr/local/src/grav-faunalia/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPageContentPr...', Object(RocketTheme\Toolbox\Event\Event)) #8 /usr/local/src/grav-faunalia/system/src/Grav/Common/Grav.php(365): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPageContentPr...', Object(RocketTheme\Toolbox\Event\Event)) #9 /usr/local/src/grav-faunalia/system/src/Grav/Common/Page/Page.php(696): Grav\Common\Grav->fireEvent('onPageContentPr...', Object(RocketTheme\Toolbox\Event\Event)) #10 /usr/local/src/grav-faunalia/system/src/Grav/Common/Page/Page.php(568): Grav\Common\Page\Page->content() #11 /usr/local/src/grav-faunalia/user/plugins/social-seo-metatags/social-seo-metatags.php(72): Grav\Common\Page\Page->summary() #12 /usr/local/src/grav-faunalia/vendor/symfony/event-dispatcher/EventDispatcher.php(212): Grav\Plugin\SocialSEOMetaTagsPlugin->onPageInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onPageInitializ...', Object(RocketTheme\Toolbox\Event\EventDispatcher)) #13 /usr/local/src/grav-faunalia/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) #14 /usr/local/src/grav-faunalia/vendor/rockettheme/toolbox/Event/src/EventDispatcher.php(23): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) #15 /usr/local/src/grav-faunalia/system/src/Grav/Common/Grav.php(365): RocketTheme\Toolbox\Event\EventDispatcher->dispatch('onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) #16 /usr/local/src/grav-faunalia/system/src/Grav/Common/Processors/PagesProcessor.php(32): Grav\Common\Grav->fireEvent('onPageInitializ...', Object(RocketTheme\Toolbox\Event\Event)) #17 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PagesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #18 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #19 /usr/local/src/grav-faunalia/system/src/Grav/Common/Processors/TwigProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #20 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TwigProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #21 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #22 /usr/local/src/grav-faunalia/system/src/Grav/Common/Processors/AssetsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #23 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\AssetsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #24 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #25 /usr/local/src/grav-faunalia/system/src/Grav/Common/Processors/SchedulerProcessor.php(29): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #26 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\SchedulerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #27 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #28 /usr/local/src/grav-faunalia/system/src/Grav/Common/Processors/BackupsProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #29 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\BackupsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #30 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #31 /usr/local/src/grav-faunalia/system/src/Grav/Common/Processors/TasksProcessor.php(59): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #32 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\TasksProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #33 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #34 /usr/local/src/grav-faunalia/system/src/Grav/Common/Processors/RequestProcessor.php(52): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #35 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\RequestProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #36 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #37 /usr/local/src/grav-faunalia/system/src/Grav/Common/Processors/ThemesProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #38 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ThemesProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #39 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #40 /usr/local/src/grav-faunalia/system/src/Grav/Common/Processors/PluginsProcessor.php(30): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #41 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\PluginsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #42 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #43 /usr/local/src/grav-faunalia/system/src/Grav/Common/Processors/InitializeProcessor.php(78): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #44 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\InitializeProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #45 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #46 /usr/local/src/grav-faunalia/system/src/Grav/Common/Processors/DebuggerProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #47 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\DebuggerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #48 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #49 /usr/local/src/grav-faunalia/system/src/Grav/Common/Processors/ErrorsProcessor.php(27): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #50 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ErrorsProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #51 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #52 /usr/local/src/grav-faunalia/system/src/Grav/Common/Processors/LoggerProcessor.php(48): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #53 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\LoggerProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #54 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #55 /usr/local/src/grav-faunalia/system/src/Grav/Common/Processors/ConfigurationProcessor.php(28): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #56 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(45): Grav\Common\Processors\ConfigurationProcessor->process(Object(Nyholm\Psr7\ServerRequest), Object(Grav\Framework\RequestHandler\RequestHandler)) #57 /usr/local/src/grav-faunalia/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(57): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #58 /usr/local/src/grav-faunalia/system/src/Grav/Common/Grav.php(249): Grav\Framework\RequestHandler\RequestHandler->handle(Object(Nyholm\Psr7\ServerRequest)) #59 /usr/local/src/grav-faunalia/index.php(53): Grav\Common\Grav->process() #60 {main} [] []

**Comment by OleVik** [comment]
I'd advise against a regular background-image, as it's liable to conflict with Reveal.js. Did you consider [Changing the footer](https://github.com/OleVik/grav-plugin-presentation/blob/master/ADVANCED.md#changing-the-footer)?

**Comment by pcav** [comment]
Yes, I tried, but the default doesn't look good. I used to use a background logo in revealjs, I should look for the syntax I used.
